### ISSUE TITLE
(desktop)Performance issues on administration,configuration and master modules.

### ISSUE THREAD

**Issue by brainkid92** [auditplus/auditplus-ui#117]
1.auto complete option panel not open in user list component.
2.expression  has  change after checked error on user form component while opening form.
3. ctrl + s method trigger save request while form is not valid on user,branch, voucher numbering and financial year component.
4. No autocomplete input on list page of voucher model.
5.No autocomplete input on list page of print model.
6. ctrl + s trigger save request form not yet valid in print model in configuration module.
7. Auto focus on auto complete input not working in ledger list component.
8. Auto focus not working in ledger form component first input field.
9.Auto focus not working list page of ledger group component.
10.Auto focus not working first input field of ledger group form component.
11.Auto focus not working product form list page component.
12.Auto focus not working on first input field of product form component.
13.TabIndex mismatching in product form component.
14.apd-form error in unit-list component
15. type number input field increase number count on every navigation key event on tax form.
16.Tax form flex need to fix.

**Comment by hchockarprasad** [comment]
Closing this for now.
